services:
  redis:
    image: redis

  dramatiq:
    build:
      context: .
      dockerfile: dramatiq.Dockerfile
    volumes:
      - type: volume
        source: conversion-files
        target: /mnt/files

  fastapi-application:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - dramatiq
    volumes:
      - type: volume
        source: conversion-files
        target: /mnt/files

volumes:
  conversion-files:
